[build-system]
requires =  ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 80

[tool.black]
line-length = 80

[tool.pytest.ini_options]
testpaths = ["test"]
