data:
  data_folder: "./datasets"
  dataset: ICEWS18
  hist_len: 3
  bidirectional: true
  different_unknowns: true
  complement_val_and_test: true
  shuffle: true

model:
  arch: evokg
  hidden_size: 200
  num_layers: 3
  dropout: 0.2
  alpha: 1.0

save_folder_path: "./saved_models/evokg-ICEWS18"
patient: 5
lr: 1.0e-3
weight_decay: 1.0e-5
grad_norm: 1.0
val_test: false