data:
  data_folder: "./datasets/ICEWS18"
  hist_len: 6 
  bidirectional: true
  different_unknowns: true
  complement_val_and_test: true
  shuffle: true

model:
  arch: tkgl.models.rerank.TripletRerank
  backbone: 
    arch: tkgl.models.regcn.REGCN
    hidden_size: 200
    num_layers: 2
    kernel_size: 3
    channels: 50
    dropout: 0.2
    norm_embeds: true
  k: 10
  num_heads: 4
  dropout: 0.2
  finetune: false
  pretrained_backbone: null

  alpha: 0.7
  beta: 0.8

training:
  patient: 5
  lr: 1.0e-3
  weight_decay: 1.0e-5
  grad_norm: 1.0