data:
  data_folder: "/home/wangshichao/workspace/temporal-knowledge-graph-learning/datasets"
  dataset: null 
  hist_len: 3 
  bidirectional: true
  different_unknowns: true
  complement_val_and_test: true
  shuffle: true

model:
  arch: refine
  hidden_size: 200
  num_layers: 2
  kernel_size: 3
  channels: 50
  dropout: 0.2
  alpha: 0.7
  beta: 0.8

save_folder_path: null
patient: 5
lr: 1.0e-3